In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

In [2]:
cities = pd.read_csv("out_data/cities.csv")
cities

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,puerto ayora,-0.74,-90.35,72.00,84,92,4.00,EC,1594235256
1,1,bengkulu,-3.80,102.27,74.80,90,84,4.81,ID,1594235257
2,2,marsabit,2.33,37.99,72.88,51,99,19.89,KE,1594235257
3,3,kaitangata,-46.28,169.85,44.01,81,91,14.00,NZ,1594235257
4,4,leningradskiy,69.38,178.42,45.30,78,0,7.29,RU,1594235257
...,...,...,...,...,...,...,...,...,...,...
552,552,bereda,43.27,-7.54,64.99,74,12,10.00,ES,1594235370
553,553,bundaberg,-24.85,152.35,57.20,87,9,8.05,AU,1594235370
554,554,winnemucca,40.97,-117.74,78.80,16,1,4.70,US,1594235360
555,555,awjilah,29.11,21.29,82.56,50,0,19.60,LY,1594235371
556,556,key west,24.56,-81.78,91.40,59,20,10.29,US,1594235111

In [3]:
gmaps.configure(api_key=g_key)

g_key

'AIzaSyD7MVJgDRmX5BHZi4T9e-auIzpiCUZC5fk'

In [4]:
citylocation = cities[["Lat", "Lng"]]
humidity = cities["Humidity"]
figure = gmaps.figure()
heat_layer = gmaps.heatmap_layer(citylocation, weights=humidity, dissipating=False, max_intensity=350, point_radius=7)

figure.add_layer(heat_layer)

print(figure)
print(heat_layer)

Figure(layout=FigureLayout(height='420px'))
WeightedHeatmap(data_bounds=[(-48.470442105507125, -179.99999), (85.0, 179.99999)], dissipating=False, locations=[(-0.74, -90.35), (-3.8, 102.27), (2.33, 37.99), (-46.28, 169.85), (69.38, 178.42), (57.79, -152.41), (-45.58, -72.07), (-46.6, 168.33), (-42.78, 147.06), (-42.88, 147.33), (8.55, 39.27), (62.23, -6.59), (-38.0, -57.56), (-35.33, -72.42), (-2.89, -40.12), (-20.22, -70.14), (78.22, 15.64), (-33.59, 26.89), (63.84, -22.43), (18.44, 1.41), (28.65, 70.66), (-24.79, -50.01), (71.29, -156.79), (54.43, -124.25), (50.67, -120.32), (3.07, 172.79), (37.1, -113.58), (-34.6, 138.73), (71.97, 102.5), (-1.57, 9.26), (5.95, 80.54), (37.46, -122.43), (-23.12, -134.97), (14.2, 24.67), (62.57, 11.38), (-54.8, -68.3), (-9.8, -139.03), (42.16, -72.33), (22.08, -159.32), (-33.93, 18.42), (-33.65, 115.33), (7.92, 98.33), (-41.87, -73.82), (31.52, 75.35), (52.5, 73.1), (-33.92, 25.57), (57.31, 88.17), (-20.23, 164.02), (47.26, 39.87), (-13.7, -76.22), (-22.97, -42.03), (42.1, -79.24), (-4.35, 152.26), (-33.7, -53.46), (-53.15, -70.92), (22.89, -109.91), (62.46, -114.35), (8.12, -63.55), (-6.53, 110.7), (33.19, -82.53), (-26.65, 15.16), (70.47, -68.59), (64.38, -173.3), (54.77, -101.86), (-22.67, 167.48), (63.84, 23.13), (-10.45, 161.92), (47.67, -52.73), (-8.47, 29.66), (18.38, 103.66), (-29.68, -53.81), (22.55, 114.07), (27.04, 14.43), (13.17, 44.58), (-46.19, 168.86), (34.64, -120.46), (65.97, 78.37), (55.34, -131.65), (15.74, -96.47), (-30.18, -50.21), (-33.01, 17.94), (65.61, -37.64), (16.45, -85.85), (61.99, 5.14), (50.7, -127.42), (4.87, -2.24), (63.19, 64.42), (-20.73, 139.5), (-46.13, 167.68), (5.35, -0.62), (32.67, -17.1), (-20.74, 116.85), (47.91, 123.5), (14.9, -24.5), (67.63, 134.63), (60.14, -45.24), (-33.02, 27.91), (3.08, -59.95), (72.79, -56.15), (55.1, -105.28), (-28.55, 16.43), (56.83, 86.63), (-34.42, 19.23), (50.68, 156.12), (53.57, 142.95), (41.37, -73.41), (46.41, -105.84), (-37.62, -73.65), (51.26, -80.61), (15.44, 119.9), (26.33, 43.98), (-38.07, 174.82), (-23.13, 150.73), (14.97, 8.89), (22.29, 114.16), (-0.6, 73.08), (69.49, 88.4), (40.6, -124.16), (42.6, -73.97), (46.36, 8.97), (69.7, 170.31), (62.51, 65.89), (17.49, 44.13), (-4.28, -55.98), (36.66, 51.42), (-18.06, 13.84), (48.65, -53.11), (48.61, 32.98), (-24.59, 27.41), (60.92, -46.05), (-21.21, -159.78), (53.05, 158.65), (69.22, -51.1), (25.02, 37.27), (-16.48, -151.75), (-3.67, 152.43), (70.37, 31.11), (5.41, 100.34), (64.89, -23.71), (56.45, 138.17), (77.48, -69.36), (31.45, 12.98), (34.94, -79.3), (47.1, -56.38), (-19.55, 169.27), (45.23, 147.88), (8.5, -82.43), (59.7, 30.79), (-28.77, 114.6), (-32.5, 137.77), (63.44, -20.27), (-9.08, 143.21), (8.07, 98.91), (-5.07, 32.05), (53.77, 87.61), (29.13, 15.95), (18.39, 42.45), (61.56, 45.93), (3.78, 72.97), (17.02, 54.09), (43.41, -124.22), (8.0, 124.29), (10.4, 5.47), (-0.41, -65.02), (30.0, -91.82), (69.45, -133.04), (44.02, 144.27), (5.56, 95.32), (20.52, -13.05), (-20.52, 57.52), (10.88, 122.49), (-10.17, 123.58), (68.75, 161.3), (42.74, -84.62), (-29.66, 17.89), (46.32, -79.47), (65.28, -126.83), (71.92, 114.08), (57.45, 97.32), (4.14, 96.13), (-25.18, 27.27), (13.22, -59.52), (-32.25, 148.62), (49.55, 17.73), (9.49, 50.81), (30.15, -85.57), (-21.2, -175.2), (70.86, 29.09), (-43.3, -65.1), (-13.88, 167.55), (-29.95, -71.34), (-22.12, 14.28), (-6.64, -51.99), (-8.27, -72.74), (38.93, 100.45), (39.1, -76.85), (-21.36, 55.77), (47.6, -53.26), (16.86, -99.89), (57.05, -135.33), (68.82, -51.19), (7.77, -72.22), (46.68, 113.28), (70.95, 27.35), (53.88, 67.42), (-20.33, -40.29), (-20.32, 118.57), (55.27, 66.49), (-38.6, 145.59), (-20.21, 57.76), (-25.24, 130.99), (-7.84, -79.15), (3.46, 8.55), (-17.73, -149.15), (51.03, -4.22), (19.21, -69.34), (55.74, -97.86), (63.75, -68.51), (22.57, 59.53), (6.77, 79.88), (-7.71, -66.98), (5.4, 26.49), (37.72, -25.43), (-38.95, -68.06), (24.8, 125.28), (-24.87, 113.63), (38.52, -28.7), (34.88, -76.9), (71.69, 128.87), (40.16, -8.33), (9.5, 35.5), (64.75, 177.48), (35.13, 140.3), (-14.27, 50.17), (38.37, 34.03), (70.63, 147.92), (-35.57, 138.62), (40.04, -111.73), (63.45, 120.32), (64.84, -147.72), (-8.93, 125.41), (19.73, -155.09), (63.05, 179.32), (-34.0, 24.73), (-20.34, 57.76), (-28.65, 153.62), (64.86, -147.8), (-3.4, -78.55), (50.32, 11.92), (13.28, -88.55), (47.79, -64.94), (43.74, 135.29), (-37.83, 140.77), (69.31, 16.12), (34.17, 77.58), (37.02, -7.93), (-34.73, 135.87), (21.5, -158.02), (51.23, -58.65), (6.5, 2.6), (46.7, -75.45), (56.67, 124.65), (-15.32, -49.12), (-26.11, -49.81), (-20.41, 57.7), (-0.91, 122.88), (20.5, -10.07), (-17.02, -72.01), (58.81, -122.7), (41.76, 86.15), (-0.61, -47.36), (8.41, 48.48), (57.02, 82.07), (37.73, -25.67), (-38.55, -58.74), (42.8, 93.45), (14.4, 46.47), (25.68, -100.25), (45.52, -122.68), (-21.15, 55.28), (10.34, -68.74), (-34.04, 23.05), (-40.57, -73.15), (27.91, -15.45), (10.57, 72.64), (58.52, -117.14), (51.77, 32.25), (-7.96, 145.78), (39.05, -27.98), (68.22, -135.01), (-33.87, 151.21), (59.57, 150.8), (56.91, 12.49), (43.05, -74.34), (-25.24, -54.0), (29.9, 69.25), (-14.66, 17.69), (43.13, -80.75), (-0.13, -67.09), (-7.2, 146.65), (11.67, 92.75), (40.7, -99.08), (27.04, -82.24), (-13.85, 136.42), (18.74, 7.39), (50.2, -66.38), (30.48, -115.95), (26.18, 127.76), (49.68, -83.67), (28.37, 129.48), (-19.0, -57.6), (66.83, 70.83), (73.51, 80.55), (28.66, -17.92), (35.0, 132.22), (32.69, 128.84), (35.73, 140.83), (-28.24, -48.67), (-2.57, 150.8), (-34.58, 150.86), (-12.58, 13.41), (49.14, 56.49), (-11.1, -77.61), (-35.72, 150.18), (39.79, 37.0), (-2.02, 147.27), (37.72, 20.83), (31.47, -97.11), (41.54, -8.62), (45.02, -93.22), (25.29, 51.53), (64.7, 43.39), (42.58, -72.0), (-14.47, 132.27), (66.04, -17.34), (42.25, -75.83), (21.64, 69.61), (14.3, -91.92), (61.73, 130.28), (61.22, -149.9), (-3.35, -64.71), (52.08, 15.63), (-9.17, -60.63), (-34.53, 20.04), (24.14, 67.45), (50.12, -5.54), (20.7, -105.2), (-11.78, 19.92), (-9.67, -35.74), (32.81, -98.11), (21.35, -158.09), (34.41, -119.86), (1.74, 98.78), (64.18, -51.72), (-5.36, 104.97), (44.06, -103.15), (36.21, 57.68), (-2.97, 119.9), (1.24, 23.62), (27.2, 60.68), (47.7, 128.9), (40.43, 71.72), (40.62, 20.78), (20.2, 1.01), (34.98, 139.87), (17.42, 121.44), (36.62, -121.92), (-19.8, -174.35), (-5.67, 132.75), (-5.56, -80.82), (-31.47, 19.78), (-23.65, -70.4), (-23.7, 133.88), (45.52, 27.32), (27.65, 74.38), (50.27, -5.05), (65.7, 82.47), (-39.63, -72.33), (-13.97, 28.68), (-9.88, -56.09), (13.76, -87.35), (65.42, -52.9), (59.12, 159.97), (59.36, 5.22), (51.32, 42.77), (-21.15, 149.2), (37.08, 33.25), (18.22, 42.51), (-12.9, 45.08), (4.38, -7.72), (11.92, 109.16), (54.43, 31.9), (12.63, 80.17), (-45.87, 170.5), (5.28, 115.24), (14.69, -17.44), (69.53, 31.17), (10.17, 40.65), (17.17, 75.97), (28.45, 75.82), (-16.52, -151.75), (49.71, 12.09), (-6.22, 155.63), (-6.88, 112.21), (19.22, -104.7), (14.53, 20.92), (60.87, 60.42), (56.49, 60.13), (54.28, -0.4), (-17.71, -39.25), (-36.72, -73.12), (39.36, -9.38), (63.9, 122.76), (39.18, -84.53), (-26.72, 27.1), (39.1, 22.9), (30.79, 31.0), (-31.39, -58.02), (49.09, 140.25), (60.47, 166.1), (-25.17, 45.05), (62.58, 6.13), (-6.43, 39.55), (-33.87, 151.21), (63.44, 53.58), (58.95, 36.6), (36.37, 6.61), (-21.64, -41.05), (48.01, 91.64), (-0.36, 42.55), (-24.0, -51.32), (-33.23, -54.38), (3.87, -67.92), (6.52, 14.3), (6.37, 126.17), (-0.73, -47.85), (30.22, -90.9), (39.15, -123.21), (57.8, 158.67), (46.62, 10.7), (-5.55, 150.14), (-25.27, 23.28), (49.5, -115.77), (50.23, -63.6), (-12.53, 27.88), (6.12, 81.12), (28.92, 80.33), (41.17, -74.05), (54.72, 135.31), (36.62, 101.77), (30.8, -81.69), (43.65, 51.2), (52.87, -104.62), (-3.2, -52.21), (35.3, 70.83), (-41.07, 145.92), (5.89, 95.32), (54.95, 48.28), (46.68, -73.92), (43.75, 24.38), (25.53, -103.25), (9.84, -83.87), (47.66, 33.71), (27.72, 85.32), (-1.95, 18.27), (-5.2, -35.46), (-16.92, 145.77), (-2.68, 111.62), (-9.44, 147.18), (27.11, 110.0), (-10.62, 150.67), (53.02, 32.39), (29.58, -9.5), (-21.34, 55.48), (53.25, 40.29), (13.59, -89.83), (9.92, -11.45), (8.57, 81.23), (7.19, 8.13), (2.43, 103.84), (25.26, 63.47), (-45.87, -67.5), (34.02, 44.15), (20.93, -17.03), (39.02, 31.15), (33.73, 135.98), (26.03, 89.97), (-16.54, 28.71), (-8.43, 114.33), (-34.72, -55.95), (-17.8, -63.17), (27.92, 96.17), (-33.87, 121.9), (53.75, 41.02), (40.8, -124.16), (-19.77, -43.85), (62.6, 29.76), (-17.53, -149.33), (18.45, -78.17), (-9.09, -78.58), (37.04, -100.92), (-17.51, -149.49), (38.42, -121.42), (44.93, -68.65), (60.4, -1.35), (16.78, 94.73), (18.22, -63.06), (16.83, 99.8), (61.68, 64.48), (2.62, 44.89), (49.64, -1.57), (4.42, -7.35), (56.91, 118.26), (-17.88, 36.89), (-34.48, -54.33), (66.0, 111.5), (-0.95, 100.35), (10.33, 98.83), (46.49, 135.88), (0.74, 30.04), (-10.0, 38.98), (52.79, 89.9), (22.81, -80.08), (-33.08, -68.47), (53.51, 142.97), (37.57, 126.98), (-27.45, 23.43), (-6.22, -57.75), (12.6, 37.47), (-16.98, -65.13), (34.04, -5.0), (29.97, 40.21), (-22.28, 166.46), (58.84, 50.85), (39.45, -86.18), (66.15, -65.71), (2.74, 23.78), (43.3, 124.33), (-19.06, -169.92), (47.31, -122.0), (5.88, -10.05), (-1.2, -46.02), (33.9, -118.08), (-3.77, -61.64), (10.37, 10.73), (21.46, -71.14), (-46.1, 168.94), (8.93, 8.6), (64.25, -15.21), (37.35, -108.59), (50.1, 1.83), (9.53, 31.66), (43.27, -7.54), (-24.85, 152.35), (40.97, -117.74), (29.11, 21.29), (24.56, -81.78)], max_intensity=350.0, point_radius=7.0, weights=[84, 90, 51, 81, 78, 59, 60, 83, 92, 93, 75, 81, 70, 60, 69, 67, 70, 45, 76, 17, 44, 89, 86, 41, 46, 77, 9, 78, 54, 87, 87, 68, 65, 49, 66, 75, 74, 66, 69, 81, 88, 94, 75, 79, 70, 82, 94, 73, 69, 68, 57, 70, 82, 93, 92, 45, 55, 51, 78, 74, 67, 100, 84, 73, 62, 93, 82, 63, 49, 86, 93, 84, 16, 53, 83, 82, 69, 93, 55, 83, 66, 61, 79, 88, 93, 86, 70, 54, 83, 83, 72, 26, 67, 83, 90, 82, 54, 54, 68, 72, 36, 96, 72, 93, 95, 94, 27, 74, 37, 76, 18, 94, 87, 23, 79, 68, 81, 82, 59, 57, 75, 67, 13, 53, 83, 43, 84, 67, 66, 58, 69, 100, 43, 59, 81, 79, 93, 94, 73, 89, 56, 50, 66, 77, 100, 94, 70, 72, 100, 80, 76, 88, 100, 42, 91, 25, 56, 68, 68, 88, 68, 90, 82, 60, 70, 100, 96, 64, 20, 60, 83, 80, 54, 55, 35, 51, 51, 71, 78, 89, 59, 62, 93, 93, 70, 66, 94, 100, 45, 94, 67, 62, 41, 93, 26, 43, 68, 67, 74, 82, 43, 32, 62, 100, 77, 65, 30, 76, 91, 60, 45, 57, 100, 61, 100, 79, 41, 87, 58, 83, 47, 93, 68, 37, 82, 82, 73, 83, 96, 67, 99, 63, 95, 88, 68, 79, 87, 31, 66, 82, 100, 88, 68, 42, 60, 93, 76, 81, 96, 52, 93, 90, 87, 81, 37, 69, 54, 73, 69, 88, 34, 90, 24, 92, 60, 85, 7, 70, 87, 57, 72, 42, 92, 68, 79, 21, 37, 59, 55, 68, 44, 71, 87, 33, 79, 67, 91, 88, 82, 87, 93, 95, 67, 88, 93, 42, 37, 52, 70, 78, 79, 46, 54, 93, 26, 88, 59, 94, 27, 94, 77, 62, 87, 78, 91, 90, 94, 68, 77, 87, 84, 60, 67, 100, 72, 81, 44, 52, 82, 52, 84, 94, 62, 51, 51, 58, 82, 55, 87, 87, 66, 87, 28, 87, 82, 93, 62, 37, 74, 53, 65, 64, 84, 58, 94, 34, 16, 89, 79, 25, 97, 25, 53, 9, 100, 85, 68, 94, 82, 53, 33, 72, 52, 64, 55, 93, 76, 93, 52, 30, 54, 91, 97, 62, 27, 93, 37, 56, 88, 84, 78, 91, 74, 90, 100, 74, 87, 24, 80, 47, 79, 100, 77, 86, 79, 24, 75, 77, 88, 61, 76, 83, 63, 52, 62, 64, 87, 62, 98, 100, 76, 81, 94, 93, 72, 84, 32, 54, 63, 84, 90, 92, 60, 90, 70, 77, 55, 39, 92, 63, 89, 57, 52, 93, 42, 100, 72, 92, 93, 75, 75, 30, 73, 59, 82, 91, 66, 57, 7, 49, 33, 61, 67, 83, 56, 69, 83, 97, 100, 91, 87, 92, 22, 68, 85, 58, 91, 82, 94, 94, 68, 53, 11, 88, 76, 94, 83, 52, 88, 87, 71, 85, 100, 75, 77, 38, 67, 61, 74, 70, 32, 61, 34, 78, 81, 92, 62, 69, 61, 77, 93, 84, 72, 87, 93, 62, 83, 98, 100, 78, 84, 88, 59, 40, 95, 83, 52, 59, 93, 62, 29, 10, 82, 95, 71, 93, 78, 58, 100, 75, 88, 75, 54, 62, 61, 80, 83, 82, 81, 13, 80, 80, 74, 87, 16, 50, 59])

In [5]:
#Create new DataFrame fitting weather criteriaÂ¶
#Narrow down the cities to fit weather conditions.
#Drop any rows will null values.

In [6]:
# Narrow down cities that fit criteria i.e. Max temp less than 80 but greater than 70 with wind speeds less than 10mph
#...and drop any results with null values. Display results

CriteriaCities = cities.loc[(cities["Max Temp"] < 80) & 
                                    (cities["Max Temp"] > 70) \
                                    & (cities["Wind Speed"]<10) \
                                    & (cities["Cloudiness"]==0)].dropna()
#check to make sure code works properly, visually. 50 columns is enough to see per the .head function. 
CriteriaCities.head(50)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
29,29,omboue,-1.57,9.26,73.26,87,0,7.67,GA,1594235262
68,68,kaputa,-8.47,29.66,70.20,49,0,3.78,ZM,1594235271
86,86,igrim,63.19,64.42,71.89,70,0,2.51,RU,1594235274
90,90,ponta do sol,32.67,-17.10,73.99,72,0,2.98,PT,1594235275
121,121,andra,62.51,65.89,74.28,67,0,5.21,RU,1594235281
162,162,kontagora,10.40,5.47,77.18,82,0,3.11,NG,1594235289
229,229,lata,40.16,-8.33,78.01,67,0,4.00,PT,1594235154
275,275,hami,42.80,93.45,79.38,21,0,9.04,CN,1594235312
388,388,boueni,-12.90,45.08,75.20,88,0,2.24,YT,1594235336
406,406,polunochnoye,60.87,60.42,71.20,75,0,3.91,RU,1594235340
409,409,caravelas,-17.71,-39.25,76.41,61,0,5.70,BR,1594235340
416,416,tanta,30.79,31.00,72.10,87,0,5.75,EG,1594235342
424,424,yarega,63.44,53.58,75.11,72,0,6.02,RU,1594235344
458,458,saint-michel-des-saints,46.68,-73.92,78.01,7,0,1.01,CA,1594235351
464,464,inongo,-1.95,18.27,75.38,56,0,0.63,CD,1594235352
487,487,siavonga,-16.54,28.71,70.39,52,0,4.36,ZM,1594235357
533,533,belaya kholunitsa,58.84,50.85,73.49,95,0,6.67,RU,1594235367

In [7]:
#Hotel MapÂ¶
#store into variable named hotel_df.
#Add a "Hotel Name" column to the DataFrame.
#Set parameters to search for hotels with 5000 meters.
#Hit the Google Places API for each city's coordinates.
#Store the first Hotel result into the DataFrame.
#Plot markers on top of the heatmap.

In [8]:
#Store into variable named hotel_df
hotel_df = CriteriaCities[["City", "Country", "Lat", "Lng"]].copy()

hotel_df

                        City Country    Lat    Lng
29                    omboue      GA  -1.57   9.26
68                    kaputa      ZM  -8.47  29.66
86                     igrim      RU  63.19  64.42
90              ponta do sol      PT  32.67 -17.10
121                    andra      RU  62.51  65.89
162                kontagora      NG  10.40   5.47
229                     lata      PT  40.16  -8.33
275                     hami      CN  42.80  93.45
388                   boueni      YT -12.90  45.08
406             polunochnoye      RU  60.87  60.42
409                caravelas      BR -17.71 -39.25
416                    tanta      EG  30.79  31.00
424                   yarega      RU  63.44  53.58
458  saint-michel-des-saints      CA  46.68 -73.92
464                   inongo      CD  -1.95  18.27
487                 siavonga      ZM -16.54  28.71
533        belaya kholunitsa      RU  58.84  50.85

In [9]:
#Hotel Name
hotel_df["Hotel Name"] = ""
hotel_df

                        City Country    Lat    Lng Hotel Name
29                    omboue      GA  -1.57   9.26
68                    kaputa      ZM  -8.47  29.66
86                     igrim      RU  63.19  64.42
90              ponta do sol      PT  32.67 -17.10
121                    andra      RU  62.51  65.89
162                kontagora      NG  10.40   5.47
229                     lata      PT  40.16  -8.33
275                     hami      CN  42.80  93.45
388                   boueni      YT -12.90  45.08
406             polunochnoye      RU  60.87  60.42
409                caravelas      BR -17.71 -39.25
416                    tanta      EG  30.79  31.00
424                   yarega      RU  63.44  53.58
458  saint-michel-des-saints      CA  46.68 -73.92
464                   inongo      CD  -1.95  18.27
487                 siavonga      ZM -16.54  28.71
533        belaya kholunitsa      RU  58.84  50.85

In [10]:
#Parameters to be set
parameters = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}
#check to see paramters code works
parameters

{'radius': 5000,
 'types': 'lodging',
 'key': 'AIzaSyD7MVJgDRmX5BHZi4T9e-auIzpiCUZC5fk'}

In [11]:
#Hit the Google Places API for each city's coordinates.
 
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]
    parameters["location"] = f"{lat},{lng}"
    #Reference the google data
    URL="https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    URLrequest = requests.get(URL, params=parameters)
    #Jsonify
    URLrequest=URLrequest.json()
    
    try:
        hotel_df.loc[index, "Hotel Name"] = URLrequest["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
hotel_df

Missing field/result... skipping.

,City,Country,Lat,Lng,Hotel Name
29,omboue,GA,-1.57,9.26,Hotel Olako
68,kaputa,ZM,-8.47,29.66,Chelelwa Charlets
86,igrim,RU,63.19,64.42,Obshchezhitiye Uchebno-Proizvodstvennogo Tsentra
90,ponta do sol,PT,32.67,-17.10,Hotel do Campo
121,andra,RU,62.51,65.89,"Gostinitsa ""Ob'"""
162,kontagora,NG,10.40,5.47,City Gate Inn
229,lata,PT,40.16,-8.33,Casa Maquia
275,hami,CN,42.80,93.45,Laoyutang Resort
388,boueni,YT,-12.90,45.08,Auberge bouloulou( inter djasmire )
406,polunochnoye,RU,60.87,60.42,
409,caravelas,BR,-17.71,-39.25,Pousada dos Navegantes
416,tanta,EG,30.79,31.00,Hesham & Fouad Pharma Group Pharmacies
424,yarega,RU,63.44,53.58,Gostitsa Uyut
458,saint-michel-des-saints,CA,46.68,-73.92,Motel Du Mont trinity
464,inongo,CD,-1.95,18.27,Hotel Du Lac
487,siavonga,ZM,-16.54,28.71,Lavongora Waterfront Lodge
533,belaya kholunitsa,RU,58.84,50.85,Greyt-Fild

In [12]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [17]:
# Add marker layer on top of heat map
marker = gmaps.marker_layer(locations, info_box_content=hotel_info)
figure.add_layer(marker)

# Display figure
print(figure)

Figure(layout=FigureLayout(height='420px'))